### ISSUE TITLE
How to run the CODE

### ISSUE THREAD

**Issue by ghost** [iglesias/ae-project#1]
Dear Mr.Iglesias:
         when I found this project, I'm so exciting.But how to star it confused me a long time.I can't find the parameter which could used in run_cl. Could you tell me some advice? Thanks for your sharing.

**Comment by iglesias** [comment]
Hello,
run_cl can be run, for example, doing `run_cl(3, 'map_o3.txt')`.

I've tested this now successfully using Octave, 13 years after this code was developed during university for a course report :) See
![image](https://github.com/iglesias/ae-project/assets/1158006/0704e016-224c-42a0-abde-b128c3315e1c)
